# vim: set ft=ansible:
---
- name: Create the nodes
  hosts: localhost
  gather_facts: no
  connection: local
  become: False
  vars_files:
    - vars.yaml
  tasks:

  - name: Create ec2 instances
    ec2:
      image: "{{ ec2_image }}"
      region: "{{ ec2_region }}"
      key_name: "{{ ec2_keypair }}"
      instance_type: "{{ ec2_instance_type }}"
      group_id: "{{ sg_group_id }}"
      instance_tags:
        Name: "{{ cluster_id }}"
      exact_count: "{{ instances }}"
      count_tag:
        Name: "{{ cluster_id }}"
      wait: true
      volumes:
        - volume_size: 10
          device_type: gp2
          device_name: /dev/sda1
          delete_on_termination: True
        - device_name: /dev/sdb
          device_type: gp2
          volume_size: 10
          delete_on_termination: True
      assign_public_ip: yes
      vpc_subnet_id: "{{ subnet_id }}"
    register: ec2

  - name: Debug ec2 data structure
    debug: var=ec2
    when: debug_print == true

#  - name: Add hosts to ec2 group
#    add_host: name={{ item.public_dns_name }} groups=ec2
#    with_items:
#      - "{{ ec2.results.0.instances }}"
#
#  - name: debug groups variable
#    debug: var=groups
#    when: debug_print == true

  - name: Wait for SSH to come up
    wait_for: host={{ item.public_dns_name }} port=22 delay=0 timeout=600 state=started
    with_items: "{{ ec2.tagged_instances }}"
 
#  - name: Wait for successful SSH
#    command: "ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null ec2-user@{{ item }} echo host is up"
#    register: result
#    until: result.rc == 0
#    retries: 60
#    delay: 10
#    with_items: "{{ groups.ec2 }}"

  - name: Create Route 53 entries
    route53:
      command: create
      overwrite: yes
      zone: "{{ r53_zone }}"
      record: "student-{{ item.0 }}.workshop.{{ r53_zone }}"
      type: A
      ttl: 300
      value: "{{ item.1.public_ip }}"
    with_indexed_items: "{{ ec2.tagged_instances }}"

  - name: Create /opt/rhel_data directory
    command: "ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -t -t ec2-user@{{ item.public_dns_name }} sudo mkdir -p /opt/rhel_data"
    with_items: "{{ ec2.tagged_instances }}"

  - name: Enable Extras Repo
    command: "ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -t -t ec2-user@{{ item.public_dns_name }} sudo yum-config-manager --enable rhui-REGION-rhel-server-extras"
    with_items: "{{ ec2.tagged_instances }}"

  - name: Install utilities
    command: "ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -t -t ec2-user@{{ item.public_dns_name }} sudo yum -y install vim-enhanced"
    with_items: "{{ ec2.tagged_instances }}"
