# vim: set ft=ansible:
---
- name: Configure the security groups
  hosts: localhost
  gather_facts: no
  connection: local
  become: False
  vars_files:
    - vars.yaml
  tasks:
  - name: Create ec2 node security group
    ec2_group:
      region: "{{ ec2_region }}"
      vpc_id: "{{ vpc_id }}"
      name: "{{ cluster_id }}-node"
      description: "{{ cluster_id }} nodes"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 5000
        to_port: 5000
        cidr_ip: 0.0.0.0/0
      - proto: all
        group_name: "{{ cluster_id }}-node"
      rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
    register: group

  - name: Debug group data structure
    debug: var=group
    when: debug_print == true

  - name: Put group data structure in file
    copy: content="{{ group.group_id }}" dest=./group_id_var